# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
    example-workflow:
      jobs:
        - python/test:
            ensure-test-tool: true 
            fail-if-missing-tool: false 
            include-branch-in-cache-key: true 
            pypi-cache: true 
            test-tool: pytest 
            venv-cache: true 
            version: '3.7' 